### ISSUE TITLE
Add individual connection options (alternative to `connectionString`)

### ISSUE THREAD

**Issue by aleclarson** [pg-nano/pg-nano#24]
Add `host`, `port`, etc. to the `Connection` class in pg-native as well as the `dev` config in `pg-nano.config.ts`.

**Comment by P-yiush07** [comment]
Can i work on this ?

**Comment by aleclarson** [comment]
@P-yiush07 Sure, let me know if you have any questions 👍

**Comment by P-yiush07** [comment]
@aleclarson getting this error when running pnpm dev #25

**Comment by P-yiush07** [comment]
@aleclarson where to commit the changes ?

**Comment by aleclarson** [comment]
https://github.com/pg-nano/pg-nano/blob/master/src%2Fcore%2Fclient.ts#L19
https://github.com/pg-nano/pg-nano/blob/master/src%2Fconfig%2Fconfig.ts#L5
https://github.com/pg-nano/pg-nano/blob/master/src%2Fconfig%2FconfigResolver.ts#L20-L23

**Comment by P-yiush07** [comment]
@aleclarson check it PULL REQUEST:  #26
