### ISSUE TITLE
TypeError: styleText is not a function

### ISSUE THREAD

**Issue by P-yiush07** [pg-nano/pg-nano#25]
## Description
When running `pnpm dev`, the following error occurs:

TypeError: styleText is not a function
at C:\Users\Piyus\OneDrive\Desktop\pg-nano\node_modules\.pnpm\tinyrun@1.0.1\node_modules\tinyrun\bin\index.js:45:9

## Steps to Reproduce
1. Set up a project using pnpm
2. Run `pnpm dev` in the terminal

## Expected Behavior
The `pnpm dev` command should execute without errors.

**Comment by aleclarson** [comment]
Looks like tinyrun is using a new NodeJS API: https://nodejs.org/api/util.html#utilstyletextformat-text-options

Can you upgrade your Node installation?

**Comment by P-yiush07** [comment]
@aleclarson 
![Screenshot 2024-09-20 102811](https://github.com/user-attachments/assets/08e7c18f-b254-467b-95f2-1bba5a865d5f)
see now doing pnpm dev gives this error

**Comment by aleclarson** [comment]
Hmm.. seems that tinyrun doesn't work well on Windows. Can you try using `pnpm dev:core` instead? That should be enough since you're not working on any of the plugins

**Comment by P-yiush07** [comment]
hmm okkay i am more focusing on that good first issue
