### ISSUE TITLE
Create a folder of examples

### ISSUE THREAD

**Issue by samueldurantes** [pg-nano/pg-nano#36]
Create a folder of examples to facilitate life for newcomers

**Comment by aleclarson** [comment]
Sure, any particular example you're interested in?

**Comment by samueldurantes** [comment]
An example of connecting to `pg-nano`, executing some query from a random schema.

**Comment by aleclarson** [comment]
In case you missed it, there's a demo already set up:

- Example of TypeScript client use: https://github.com/pg-nano/pg-nano/blob/master/demos/exhaustive/test.ts
- Example SQL schema: https://github.com/pg-nano/pg-nano/tree/master/demos/exhaustive/sql
  - The [schema.ts](https://github.com/pg-nano/pg-nano/blob/master/demos/exhaustive/sql/schema.ts) and [typeData.ts](https://github.com/pg-nano/pg-nano/blob/master/demos/exhaustive/sql/typeData.ts) modules are both generated by pg-nano

Let me know if that's not enough
